services:
  - type: web
    name: fouani-menu-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        value: your_mongodb_connection_string  # Set this in Render dashboard 